apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: demo
      app: demo
    name: demo-service-pipeline
  spec:
    successfulBuildHistoryLimit: 2
    failedBuildHistoryLimit: 2
    source:
      git:
        uri: https://github.com/MasmoudiHamdi/HMA.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic